# Generated by Django 2.2.10 on 2020-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200323_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='infapost',
            name='image',
            field=models.FileField(blank=True, upload_to='post image'),
        ),
    ]
